language: python
python:
  - "2.7"
install:
  - sudo apt-get -qq install xvfb python-virtualenv
before_script:
  - ./setup_travis.sh
  - cd tests
script:  ./run_selenium_tests.sh
env:
# https://github.com/MoritzT/tcp-app/blob/master/components/web-animations-js/.travis.yml
  - BROWSER=Chrome-beta ARGS='-x -b Chrome -u'
  - BROWSER=Chrome-unstable ARGS='-x -b Chrome -u'
  - BROWSER=Firefox-stable ARGS='-x -b Firefox -u'
  - BROWSER=Firefox-beta ARGS='-x -b Firefox -u'
  - BROWSER=Firefox-aurora ARGS='-x -b Firefox -u'

