language: python
python:
  - "2.7"
install:
  - sudo apt-get -qq install xvfb python-virtualenv
before_script:
  - ./setup_travis.sh
  - cd tests
script:  ./run_selenium_tests.sh
env:
# https://github.com/MoritzT/tcp-app/blob/master/components/web-animations-js/.travis.yml
  - BROWSER=Chrome-beta
  - BROWSER=Chrome-unstable
  - BROWSER=Firefox-stable
  - BROWSER=Firefox-beta
  - BROWSER=Firefox-aurora

